### ISSUE TITLE
No Backpressure?

### ISSUE THREAD

**Issue by halgari** [bluemont/kria#8]
There doesn't seem to be a way in the API to support back pressure. From my readings of the docs Kria may call a callback many times, is there a way to limit it to stop returning results if I can't process them fast enough?

**Comment by halgari** [comment]
Seems like it could be supported fairly easily by not doing this: https://github.com/bluemont/kria/blob/master/src/clojure/kria/core.clj#L124

It looks like the code is executing reads as fast as it possibly can. Instead if this did something like `(clojure.core.async/put! c v (fn [_] (.read ...))` you could support back pressure pretty easily. Users could then read from `c` as slowly as they wanted, and TCP would propagate the back pressure back to the Riak server.

**Comment by halgari** [comment]
Or perhaps the call to `(.read )` could be put in a callback and handed to the user's callback. That way they can determine when to continue reading more data.

**Comment by xpe** [comment]
Thanks for the question and digging in!

> Or perhaps the call to (.read ) could be put in a callback and handed to the user's callback. That way they can determine when to continue reading more data.

I like this suggestion.

Would anyone else like to weigh in?

**Comment by xpe** [comment]
As a reason for liking the second alternative, I like the idea of not making core.async a dependency of Kria.
